name: Convert Markdown to Multiple Formats

on: 
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive texlive-xetex texlive-fonts-recommended

      - name: Convert Markdown to PDF, DOCX, and HTML
        run: |
          INPUTFILE="README"
          FILENAME="ThomasDonnellyResume"
          pandoc README.md -o README.pdf --pdf-engine=lualatex -V colorlinks=true -V urlcolor=blue -V geometry:margin=1in
          pandoc ${INPUTFILE}.md -o ${FILENAME}.docx
          pandoc ${INPUTFILE}.md -o ${FILENAME}.html
          pandoc ${INPUTFILE}.md -o ${FILENAME}.odt
          pandoc ${INPUTFILE}.md -o ${FILENAME}.txt
          pandoc ${INPUTFILE}.md -o ${FILENAME}.epub
          pandoc ${INPUTFILE}.md -o ${FILENAME}.tex

      - name: Commit and Push Generated Files
        run: |
          INPUTFILE="README"
          FILENAME="ThomasDonnellyResume"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ${FILENAME}.pdf ${FILENAME}.docx ${FILENAME}.html ${FILENAME}.odt ${FILENAME}.txt ${FILENAME}.epub ${FILENAME}.tex
          git commit -m "Automated document conversion for ${INPUTFILE}.md into ${FILENAME}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MARKDOWNTOKEN }}@github.com/TomTheTonk/Resume.git

        env:
          GITHUB_TOKEN: ${{ secrets.MARKDOWNTOKEN }}