name: Convert Markdown to Multiple Formats

on: 
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive texlive-xetex texlive-fonts-recommended

      - name: Convert Markdown to PDF, DOCX, and HTML
        run: |
          FILENAME="ThomasDonnellyResume"
          pandoc ${FILENAME}.md -o ${FILENAME}.pdf --pdf-engine=xelatex -V colorlinks=true -V urlcolor=blue
          pandoc ${FILENAME}.md -o ${FILENAME}.docx
          pandoc ${FILENAME}.md -o ${FILENAME}.html
          pandoc ${FILENAME}.md -o ${FILENAME}.odt
          pandoc ${FILENAME}.md -o ${FILENAME}.txt
          pandoc ${FILENAME}.md -o ${FILENAME}.epub
          pandoc ${FILENAME}.md -o ${FILENAME}.tex

      - name: Commit and Push Generated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ThomasDonnellyResume.pdf ThomasDonnellyResume.docx ThomasDonnellyResume.html ThomasDonnellyResume.odt ThomasDonnellyResume.txt ThomasDonnellyResume.epub ThomasDonnellyResume.tex
          git commit -m "Automated document conversion for ThomasDonnellyResume.md" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MARKDOWNTOKEN }}@github.com/TomTheTonk/Resume.git

        env:
          GITHUB_TOKEN: ${{ secrets.MARKDOWNTOKEN }}